---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ include "synology-csi.fullname" $ }}-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "synology-csi.fullname" $ }}-delete
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: test
    {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ include "synology-csi.fullname" $ }}-test
spec:
  containers:
    - command: [ "/bin/sh", "-c", "echo asdf >file && echo asdf | cmp - file" ]
      image: busybox
      name: readwrite
      volumeMounts:
        - mountPath: /data
          name: data
      workingDir: /data
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: {{ include "synology-csi.fullname" $ }}-test
